##
## bitcoin.conf configuration file. Lines beginning with # are comments.
##

#limitancestorcount=5
pruneblocks=824188

rpcthreads=64
rpcworkqueue=256

standalone=1
disablesafemode=1
minimumchainwork=0000000000000000000000000000000000000000000000000000000000000001
rest=1
rpcservertimeout=120

#start in background
daemon=0

#Required Consensus Rules for Genesis
excessiveblocksize=10000000000 #10GB
maxstackmemoryusageconsensus=100000000 #100MB

#Mining
#biggest block size you want to mine
blockmaxsize=4000000000
blockassembler=journaling  #journaling is default as of 1.0.5

#preload mempool
preload=1

# Index all transactions, prune mode don't support txindex
txindex=1

#testnet=1

#Other Sys
maxmempool=6000
dbcache=1000

#connect=0
maxconnections=8

# JSON-RPC options
server=1
rpcbind=0.0.0.0
rpcallowip=0.0.0.0/0
rpcuser=tbcuser
rpcpassword=randompasswd
rpcport=8332
port=8333

#Other Block
threadsperblock=6

#Other Tx Conf:
maxscriptsizepolicy=0
blockmintxfee=0.000060