// Copyright (c) 2024 The Bitcoin Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#ifndef BITCOIN_INTERFACES_MINING_H
#define BITCOIN_INTERFACES_MINING_H

#include "amount.h"
#include "primitives/transaction.h"
#include "uint256.h"
#include "utiltime.h"

#include <memory>
#include <optional>
#include <vector>

class Config;
class NodeContext;

class BlockValidationState;
class CBlock;
class CBlockHeader;
class CScript;

//! Reference to a block with hash and height
struct BlockRef {
    uint256 hash;
    int height;
};

//! Options for checkBlock
struct BlockCheckOptions {
    bool check_merkle_root{true};
    bool check_pow{true};
};

//! Block template interface
class BlockTemplate
{
public:
    virtual ~BlockTemplate() = default;

    virtual CBlockHeader getBlockHeader() = 0;
    virtual std::shared_ptr<CBlock> getBlockRef() = 0;
    // Block contains a coinbase transaction
    virtual CBlock getBlock() = 0;

    // Fees per transaction, not including coinbase transaction.
    virtual std::vector<Amount> getTxFees() = 0;
    // Sigop cost per transaction, not including coinbase transaction.
    virtual std::vector<int64_t> getTxSigops() = 0;

    virtual CTransactionRef getCoinbaseTx() = 0;
    virtual int getWitnessCommitmentIndex() = 0;

    /**
     * Compute merkle path to the coinbase transaction
     *
     * @return merkle path ordered from the deepest
     */
    virtual std::vector<uint256> getCoinbaseMerklePath() = 0;

    /**
     * Construct and broadcast the block.
     *
     * @returns if the block was processed, independent of block validity
     */
    virtual bool submitSolution(uint32_t version, uint32_t timestamp, uint32_t nonce, CTransactionRef coinbase) = 0;

    /**
     * Deep-copy this template (header + transaction list + fee/sigop arrays).
     * Transactions themselves are immutable (CTransactionRef = shared_ptr to
     * const), so the vtx vector is copied but its elements remain shared.
     */
    virtual std::shared_ptr<BlockTemplate> clone() = 0;
};

//! Interface giving clients (RPC, Stratum v2 Template Provider in the future)
//! ability to create block templates.
class Mining
{
public:
    using MillisecondsDouble = std::chrono::duration<double, std::chrono::milliseconds::period>;

    virtual ~Mining() = default;

    //! Returns the hash and height for the tip of this chain
    virtual std::optional<BlockRef> getTip() = 0;

    /**
     * Waits for the connected tip to change.
     *
     * @param[in] current_tip block hash of the current chain tip. Function waits
     *                        for the chain tip to differ from this.
     * @param[in] timeout     how long to wait for a new tip (default is forever)
     *
     * @retval BlockRef hash and height of the current chain tip after this call.
     * @retval std::nullopt if the node is shut down.
     */
    virtual std::optional<BlockRef> waitTipChanged(uint256 current_tip, MillisecondsDouble timeout = MillisecondsDouble::max()) = 0;

    /**
     * Waits for fees in the next block to rise, a new tip or the timeout.
     *
     * @param[in] timeout     how long to wait for a fee increase
     * @param[in] tip         block hash that the most recent template builds on
     * @param[in] fee_delta   how much total fees in the next block should rise.
     * @param[in,out] fees_before fees for the most recent template
     * @param[out] tip_changed whether a new tip arrived during the wait
     *
     * @returns true if fees increased, false if a new tip arrives or the timeout occurs
     */
    virtual bool waitFeesChanged(MillisecondsDouble timeout, uint256 tip, Amount fee_delta, Amount& fees_before, bool& tip_changed) = 0;

   /**
     * Construct a new block template
     *
     * @param[in] script_pub_key the coinbase output
     * @returns a block template
     */
    virtual std::unique_ptr<BlockTemplate> createNewBlock(const CScript& script_pub_key) = 0;

    /**
     * Submit a fully reconstructed block to validation.
     */
    virtual bool submitBlock(std::shared_ptr<CBlock> block) = 0;

    /**
     * Checks if a given block is valid.
     *
     * @param[in] block       the block to check
     * @param[in] options     verification options: the proof-of-work check can be
     *                        skipped in order to verify a template generated by
     *                        external software.
     * @param[out] reason     failure reason (BIP22)
     * @param[out] debug      more detailed rejection reason
     * @returns               whether the block is valid
     */
    virtual bool checkBlock(const CBlock& block, const BlockCheckOptions& options, std::string& reason, std::string& debug) = 0;

    //! Get internal node context. Useful for RPC and testing,
    //! but not accessible across processes.
    virtual NodeContext* context() { return nullptr; }
};

//! Return implementation of Mining interface.
std::unique_ptr<Mining> MakeMining(NodeContext& node, const Config& config);

#endif // BITCOIN_INTERFACES_MINING_H
